# Q1.
### Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

In [1]:
import pandas as pd


In [2]:
from sklearn.datasets import load_iris

In [10]:
iris = load_iris()

In [11]:
X,y = iris.data , iris.target

In [12]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size = 0.3 , random_state = 42)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [15]:
y_pred = classifier.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix

In [17]:
print(confusion_matrix(y_pred , y_test))
print(accuracy_score(y_pred , y_test))
print(classification_report(y_pred , y_test))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



# Q2.
### Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

In [19]:
from sklearn.datasets import load_boston
boston = load_boston()
X,y = boston.data , boston.target

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


# Q3.
### Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [22]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

X,y = iris.data , iris.target

k_values = range(1,31)
cv_scores = []

for k in k_values :
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn,X,y,cv=10,scoring='accuracy')
    cv_scores.append(scores.mean())
    
optimal_k = k_values[np.argmax(cv_scores)]
print(optimal_k)

13


# Q4.
### Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

load_boston dataset is been removed.

# Q5.
### Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

In [23]:
knn = KNeighborsClassifier(n_neighbors=5,weights = 'distance')
knn.fit(X_train,y_train)

KNeighborsClassifier(weights='distance')

In [24]:
y_pred = knn.predict(X_test)

In [26]:
print(accuracy_score(y_test,y_pred))

1.0


# Q6
### Implement a function to standardise the features before applying KNN classifier.

In [28]:
from sklearn.preprocessing import StandardScaler

def standardize_and_knn(X, y, n_neighbors=5):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    knn = KNeighborsClassifier(n_neighbors=n_neighbors)
    knn.fit(X_train_scaled, y_train)
    
    y_pred = knn.predict(X_test_scaled)
    
    accuracy = accuracy_score(y_test, y_pred)
    return accuracy

iris = load_iris()
X, y = iris.data, iris.target
accuracy = standardize_and_knn(X, y)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 1.00


# Q7.
### Write a Python function to calculate the euclidean distance between two points.

In [29]:
import numpy as np

def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2) ** 2))

point1 = np.array([1, 2, 3])
point2 = np.array([4, 5, 6])
distance = euclidean_distance(point1, point2)
print(f'Euclidean Distance: {distance:.2f}')

Euclidean Distance: 5.20


# Q8.
### Write a Python function to calculate the manhattan distance between two points.

In [31]:
import numpy as np

def manhattan_distance(point1, point2):
    return np.sum(np.abs(point1 - point2))

point1 = np.array([1, 2, 3])
point2 = np.array([4, 5, 6])
distance = manhattan_distance(point1, point2)
print(f'Manhattan Distance: {distance:.2f}')

Manhattan Distance: 9.00
